apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-factory-service-deploy
spec:
  selector:
    matchLabels:
      app: movie-factory-service
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: movie-factory-service
    spec:
      containers:
        - name: movie-factory-service
          image: nikmohan81/movie-factory:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: OMDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: apikey-secret
                  key: omdbi-apikey

---

apiVersion: v1
kind: Service
metadata:
  name: movie-factory-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: movie-factory-service

  ports:
    - name: http
      port: 9020

  type: ClusterIP
