
spring:
  profiles:
    active: dev

searchSize: 3
ratingBenchmark: 6.5
omdb:
  uri: http://www.omdbapi.com/
---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hourglass

---
spring:
  profiles: prod
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: hourglass

